### ISSUE TITLE
cannot import name ilorest_logger

### ISSUE THREAD

**Issue by joeomc** [HewlettPackard/ansible-ilorest-role#1]
All the example code is referencing `ilorest_logger`, which doesn't appear to be part of python-ilorest-library version 2.0.0.  I get the following error when trying the get_ilo_ip module.
```
from redfish import AuthMethod, ilorest_logger, redfish_client
ImportError: cannot import name ilorest_logger
```

**Comment by frippe75** [comment]
I'm having the same exact issue. Any plans on doing something about it?

**Comment by Yergidy** [comment]
Sorry for the slow response. We are looking into this.

**Comment by Yergidy** [comment]
The fix for this issue has been committed. Please let me know if you still are getting errors.

**Comment by Yergidy** [comment]
Closing issue
