### ISSUE TITLE
Directory description in main Readme.md file ?

### ISSUE THREAD

**Issue by donzef** [HewlettPackard/ansible-ilorest-role#10]
Would it be possible to have a detailed and accurate description of the content of different directories of this repo ?

Just wanting to grasp quickly the difference of a playbook in the example directory compared to a playbook in the ansibleredfish_playbooks....

What is the content of iloresttool_playbooks compared to ilorestlibrary_playbooks ?

Thanks

**Comment by iLORESTeam** [comment]
Sure, we will soon make it available

**Comment by donzef** [comment]
Great, the added paragraph provides valuable info.

However, I noticed that the `examples` directory is not mentioned in this new paragraph and it would be interesting to know on which Redfish library are based its playbooks.

Thanks
