### ISSUE TITLE
Yaml syntax error

### ISSUE THREAD

**Issue by berobero** [HewlettPackard/ansible-ilorest-role#12]
I just git cloned the repo, edited the hosts file and tried to run get_ahs.yml and got the yaml syntax error. I tried a few things for whitespaces but nothing seem to work. Please advise. Thank you.

Here is the error 
ansible-playbook -i hosts ilorestlibrary_playbooks/get_ahs.yml
[WARNING]: log file at /var/log/ansible.log is not writeable and we cannot create it, aborting

ERROR! Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to have been in '/appl/home/vh9989/ansible-ilorest-role-master/ilorestlibrary_playbooks/get_ahs.yml': line 20, column 14, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    enabled: True
      baseuri: "{{ baseuri }}"
             ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

**Comment by taroh77** [comment]
The sample certainly looks like a syntax error.
I think the following is the correct syntax.

```
  - name: Get ahs
    get_ahs:
      enabled: True
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      ahs_file_name: "{{ ahs_name }}"
    become : yes
    register: result
```

But, the library had `get_ahs_data` instead of `get_ahs`.
The attributes also seem to be different.

```
  - name: Get ahs
    get_ahs_data:
      name: "xxxx"
      enabled: True
      ahs_file_name: "{{ ahs_name }}"
    become : yes
    register: result
```

**Comment by iLORESTeam** [comment]
Thanks for informing. We will correct this soon.
