### ISSUE TITLE
Provide Examples for generating CSR

### ISSUE THREAD

**Issue by localleon** [HewlettPackard/ansible-ilorest-role#15]
Hey,

is it possible to generate a CSR for an ilo-device? The file `library/generateCSR.py` indicates that it's possible, but i can't figure out how to. 

Would be great if you could provide some example Ansible code. Same goes for installing a SSL Certificate. 

Thanks in advance.

**Comment by gouthamrt8** [comment]
Have same question related to csr generation and cert import.
