### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by frippe75** [HewlettPackard/ansible-ilorest-role#2]
Looks like some code was copied directly from the oneview repo.
The entire mount_vmedia_module documentation section is from oneview.

`DOCUMENTATION = '''
module: oneview_enclosure
short_description: Manage OneView Enclosure resources.
description:`
.
.
.
.

**Comment by Yergidy** [comment]
Thanks for the heads up. We will update this.

**Comment by Yergidy** [comment]
This has been fixed in commit b29a143b6cebe1ad2dae2154b3c9042fd44f4880
