### ISSUE TITLE
Ilo reset doesn't work

### ISSUE THREAD

**Issue by sebastianeidner1980** [HewlettPackard/ansible-ilorest-role#5]
CentOS Linux release 7.5.1804 (Core)
python 2.7.5
Ansible 2.6.2

We disabled the certifcate verfication and it doesn't trigger the reset. If we do it by writting our own script or use the provided hpe example it works.

If we use the ansible with restart.yml and with the libary it changes the state and shows state "ok", but on server side nothings happend.

**Comment by Yergidy** [comment]
@sebastianeidner1980 Sorry for the slow response. We will look into it. Thanks for reporting this issue.
