### ISSUE TITLE
Path for query (get_resource_directory)

### ISSUE THREAD

**Issue by Thomas-TSI** [HewlettPackard/ansible-ilorest-role#8]
We use the latest firmware on HP DL360 Gen 9 along with ilorest-3.0.1-7.x86_64.
Our path to the ressource directory is:

`   "Name":"HP RESTful Root Service",
   "Oem":{
      "Hp":{
         "@odata.type":"#HpiLOServiceExt.1.0.0.HpiLOServiceExt",
         "Links":{
            "ResourceDirectory":{
               "@odata.id":"/redfish/v1/ResourceDirectory/"
            }
         },
`
your query uses "Hpe" instead of "Hp" therefore get_resource_directory does not work for us.

regards,
Thomas

**Comment by rajeevkallur** [comment]
Thanks for informing. We will get back to you on this.  For now, please change it in the script from Hpe to Hp in the following lines of code.  
resource_uri = redfishobj.root.obj.Oem.**Hpe**.Links.ResourceDirectory['@odata.id']

**Comment by Thomas-TSI** [comment]
By the way this line doesn't work as well:
      if '#HpeiLOSnmpService.' in instance['@odata.type']:
  
because the type is "#SnmpService.1.0.0.SnmpService"

**Comment by rajeevkallur** [comment]
Noted

**Comment by Thomas-TSI** [comment]
`    for instance in resource_instances:
        #Use Resource directory to find the relevant URI
        if 'SnmpService' in instance['@odata.type']:
            snmp_service_uri = instance['@odata.id']
            break
`
This break is needed to prevent "KeyError: '@odata.type'" in the loop. After this get_resource_directory works.
